######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 2 19:39:38 2008
######################################################################

TEMPLATE = app

SOURCES += main.cpp \
	ffmpeg.cpp \
	mainwindow.cpp

HEADERS += ffmpeg.h \
	mainwindow.h

FORMS += mainwindow.ui

QT = core gui

CONFIG += debug

LIBS += -lavdevice -lavcodec -lavformat -lswscale
